### ISSUE TITLE
Text not working in IOS app in 0.2.48

### ISSUE THREAD

**Issue by nirajhi** [ivictbor/painterro#10]
Hi Ivictbor,

 First of all, thank you for this amazing widget. I am currently trying to implement paintero on my cordova app. I am able to use all the functionality but for some reason the text does not work.  When I click the text button the text box does appear but I am not able to append the text to the editable span. Could you please look into this issue. Thank you.

**Comment by ivictbor** [comment]
Hi @nirajhi 
Thank you for the report!
I tried on iPad on this fiddle https://jsfiddle.net/Levaqoeh/13/ and I am able to appear text into the span
![image](https://user-images.githubusercontent.com/1838656/35161142-fb601e70-fd47-11e7-85a4-7169630c19cf.png)
However, there is some another known issue with Apply button in text mode which is now hidden and looks like iPad does not scroll it. I am going to sort it out soon.
Could you please try the fiddle and if it works for you same as for me, then please send url with some non-working instance of painterro.

**Comment by ivictbor** [comment]
@nirajhi fixed apply button in text tool in v0.2.55, check the [demo](https://maketips.net/paste)

**Comment by nirajhi** [comment]
Hi @ivictbor,

Thank you for the quick feedback. The jsfiddle you gave works fine but the same code is not working for cordova app. I think the issue is related to the cordova. I will check into it and let you know.

**Comment by ivictbor** [comment]
Great, feel free to reopen if any
