### ISSUE TITLE
Open painterro with existing image

### ISSUE THREAD

**Issue by teckseen** [ivictbor/painterro#16]
Hi,

Sorry if this question is obvious, I cannot see how to do this from the document.

Can painterro `.show()` with existing image e.g. image data from API?

**Comment by ivictbor** [comment]
@teckseen just use 
```
Painterro().show('url to the image')
```
e.g. fiddle https://jsfiddle.net/Levaqoeh/21/

**Comment by teckseen** [comment]
Thanks @ivictbor, 

Got it working by passing in the following format `` `data:image/jpeg:base64,${image}` `` to `show()`

**Comment by teckseen** [comment]
Just finish integrating into our application. Works great. Thanks @ivictbor.
