### ISSUE TITLE
Feature request - Line tool with arrow

### ISSUE THREAD

**Issue by teckseen** [ivictbor/painterro#17]
Would love to see line tool with option for arrows. Maybe a dropdown to select arrow types

Thanks

**Comment by ivictbor** [comment]
Thanks, yeah, I have been thinking about this feature as most required from the beginning. Definitely need to give this first priority.

**Comment by kishandonepudi** [comment]
Bro can i use this in ionic with angular ? is there any sample application using this JS with angular/ionic please share......

**Comment by kishandonepudi** [comment]
+1

**Comment by Leinad4Mind** [comment]
+1 on this. Just a simple line with arrow format would be already awesome.

**Comment by ivictbor** [comment]
Added in 0.2.75
