### ISSUE TITLE
Painterro not removing event listeners after calling done

### ISSUE THREAD

**Issue by dtailor90** [ivictbor/painterro#19]
This leads to an issue of hijacking event handlers eg Drag, which causes functionality to break on the rest of the platform, even after Painterro instance is destroyed.

**Comment by akhenry** [comment]
Hi @ivictbor! You might be interested to know that we are currently using Painterro at NASA in some experimental functionality for our [open source mission control](https://github.com/nasa/openmct) software. We're grateful for the work you've put into Painterro.

To resolve this issue for now we are shimming Painterro to support cleaning up of event handlers - https://github.com/nasa/openmct/pull/1986/commits/54896d5df17adaaae95c8651a2a878dde05473fe . A possible modification to Painterro which would help to make it a little more self contained would be to have Painterro only attach its listeners on `show()`, and to clean them up on `hide()`.

**Comment by akhenry** [comment]
https://github.com/nasa/openmct/pull/1986/commits/70a7e23f158003ceb0ac8311fe326d8c56ee7b49

**Comment by ivictbor** [comment]
@akhenry @dtailor90 
Thanks, this is a real honor for me! I will investigate what happened with listeners in nearest free time. That was an original idea to ignore all listeners on hiding and also ignore all events that was not addressed for the widget itself. 
Please let me know if you run into other issues!

**Comment by ivictbor** [comment]
@akhenry fixed in 0.2.64.
Please let me know if you run into other issues or if you would like to see some new functionality!

**Comment by akhenry** [comment]
This appears to have fixed the issue we were seeing. Thanks @ivictbor!

**Comment by ivictbor** [comment]
Great, then I am closing the issue

**Comment by kishandonepudi** [comment]
really amazing!!! project, kudos to the team.......
