### ISSUE TITLE
Is possible blur setting for small area

### ISSUE THREAD

**Issue by dechoiliev** [ivictbor/painterro#2]
Hi,

Is there a possibility to hide sensitive data to controlling pixel intensity effect(pixels on the selected area), without repeating pixel tool?

Problem is when a text in picture and it very small area for blur. Then pixelize is imperfect.

Maybe a good idea is setting for this.

![pixel_text](https://user-images.githubusercontent.com/12443425/29030550-11baa784-7b94-11e7-8d03-ae3e4a6b9fb1.png)

Thanks.

**Comment by ivictbor** [comment]
@dechoiliev Hi, thanks for the suggestion. Setting will be added in nearest release

**Comment by ivictbor** [comment]
@dechoiliev 
Now you are able to configure blur pixel size. You can done it in two ways:
1. define `pixelizePixelSize` in settings e.g.:
```
Painterro({
  pixelizePixelSize: '4', // define pixelize pixel size as 4 canvas pixels
  //or:
  // pixelizePixelSize: '50%' // define pixelize pixel size as 1/2 of minimum selection rectangle side
})
```
2. Change this setting in runtame (accepts same values):
![](https://maketips.net/media/uploads/2017/08/09/pNe3dD52nDCvhbtFpGJKhi-e5326c67.png)

**Comment by dechoiliev** [comment]
It looks perfect. Great job.
Thanks.
