### ISSUE TITLE
Feature request - warning when navigating away from unsaved image

### ISSUE THREAD

**Issue by davesmith9088** [ivictbor/painterro#21]
A useful feature would be to have a configurable warning that would display if you attempt to navigate away from an unsaved image or close the browser window.

**Comment by kishandonepudi** [comment]
+1

**Comment by Maleantes** [comment]
i think you can do that your self, if the button of cancel is not disabled, there are modifications on image and you can show a warning.

**Comment by ivictbor** [comment]
@Maleantes yes, please let me know if you need some api
