### ISSUE TITLE
NPM repository only includes commonjs2 build artifact

### ISSUE THREAD

**Issue by akhenry** [ivictbor/painterro#22]
The webpack config also produces build artifacts for UMD and others. It might be useful to also publish these (or even just the UMD one) to npm.

**Comment by ivictbor** [comment]
@akhenry added all artifacts in v0.2.65
Though I am not sure how it will be included in projects, so currently it just located under `build` directory of `npm` package.   ![](https://maketips.net/media/uploads/2018/04/18/D6deMHfvqmgZSjUbPtU5PZ-0adecc0e.png)

**Comment by akhenry** [comment]
@ivictbor Thanks for addressing this!
