### ISSUE TITLE
React with webpack:  e.defaultSize.split is not a function

### ISSUE THREAD

**Issue by afijal** [ivictbor/painterro#23]
After transitioning our web app to react, we've encountered such an issue:
![image](https://user-images.githubusercontent.com/2682379/42881115-f529e176-8a96-11e8-8c30-0ba6e8c06b68.png)
Seems like it is line 108 in params.js in your source code.

We get in randomly, 50% of time, when calling Painterro(painterroConfiguration).
Here is our painterroConfiguration json.
`{
    "translation": {
        "name": "en",
        "strings": {
            "lineColor": "Line color: ",
            "lineColorFull": "Line color",
            "fillColor": "Fill color: ",
            "fillColorFull": "Fill color",
            "alpha": "Alpha value",
            "alphaFull": "Alpha value",
            "lineWidth": "Line width: ",
            "lineWidthFull": "Line width",
            "eraserWidth": "Eraser width: ",
            "eraserWidthFull": "Eraser width",
            "textColor": "Text color: ",
            "textColorFull": "Text color",
            "fontSize": "Font size: ",
            "fontSizeFull": "Font size",
            "fontStrokeSize": "Stroke width: ",
            "fontStrokeSizeFull": "Stroke width",
            "fontStyle": "Font style: ",
            "fontStyleFull": "Font style",
            "fontName": "Font name: ",
            "fontNameFull": "Font name",
            "textStrokeColor": "Stroke color: ",
            "textStrokeColorFull": "Stroke color",
            "apply": "Apply",
            "cancel": "Cancel",
            "close": "Close",
            "clear": "Clear",
            "width": "Width",
            "height": "Height",
            "keepRatio": "Keep width/height ratio",
            "fillPageWith": "Fill page with current background color",
            "pixelSize": "P",
            "pixelSizeFull": "Pixel size",
            "resizeScale": "Scale",
            "resizeResize": "Resize",
            "backgroundColor": "Page background color",
            "pixelizePixelSize": "Pixelize pixel size",
            "wrongPixelSizeValue": "Wrong pixel size. You can enter e.g. \"20%\" which mean pixel size will be 1/5 of the selected area side, or \"4\" means 4 px",
            "tools": {
                "crop": "Crop image to selected area",
                "pixelize": "Pixelize selected area",
                "rect": "Draw rectangle",
                "ellipse": "Draw ellipse",
                "line": "Draw line",
                "rotate": "Rotate image",
                "save": "Save image",
                "load": "Load image",
                "text": "Put text",
                "brush": "Brush",
                "resize": "Resize or scale",
                "open": "Open image",
                "select": "Select area",
                "close": "Close Painterro",
                "eraser": "Eraser",
                "settings": "Settings"
            },
            "pasteOptions": {
                "fit": "Replace all",
                "extend_down": "Extend down",
                "extend_right": "Extend right",
                "over": "Paste over",
                "how_to_paste": "How to paste?"
            }
        }
    },
    "id": "scratch-pad-containter",
    "defaultTool": "brush",
    "hiddenTools": ["crop", "pixelize", "rotate", "resize", "settings", "close", "save", "text"],
    "defaultSize": "fill",
    "defaultLineWidth": 4,
    "defaultEraserWidth": 16,
    "availableLineWidths": [1,2,4,8,16],
    "availableEraserWidths": [1,2,4,8,16,64],
    "availableFontSizes": [1,2,4,8,16],
    "colorScheme": {
        "main": "rgba(0,98,217,0.6)",
        "control": "white",
        "activeControl": "rgba(230,230,230,1)",
        "inputText": "black"
    }
}
`
Switching default size to e.g. 100x100 or even removing it completely doesn't help too.

**Comment by ivictbor** [comment]
Indeed, when settings were persisted in localstorage, then on load there will be object in params.defaultSize

**Comment by ivictbor** [comment]
so you can update if you have a chance and let me know whether if fixed your problem. Thanks a lot for report and @oskarhinc thanks for investigation

**Comment by ivictbor** [comment]
Closing because of no response from author
