### ISSUE TITLE
Save in Angular

### ISSUE THREAD

**Issue by kishandonepudi** [ivictbor/painterro#24]
HI Guys,

How can i save this image into blob in angular , can you guys please guide me on this...

**Comment by ivictbor** [comment]
Hi. Did you have some issues with method described in readme?

**Comment by ivictbor** [comment]
I mean - there is nothing specific to angular... you just need to export image as blob to some variable and you can then use this value as you want, assign to state etc. So please post error if method described in spec is not worki g

**Comment by kishandonepudi** [comment]
Achieved it with the the below code,

>  let dataurl = this.dataurl;
    let pageNum = this.pageNum;
    var _this = this;
    let allpages = this.allpages;
    var ptr = Painterro({
      hiddenTools: ['crop', 'select', 'pixelize','rotate','open'],
      how_to_paste_action: 'replace_all',
      toolbarPosition: 'top',
      defaultTool: 'brush',
      defaultLineWidth: 8,
      defaultFontSize: 8,
      availableLineWidths: [1, 2, 4, 8, 16, 64],
      availableEraserWidths: [1, 2, 4, 8, 16, 64],
      availableFontSizes: [1, 2, 4, 8, 16, 64],
      activeColor: '#000000',
      colorScheme: {
        activeControl: '#e20214',
        inputText: '#000000', // change controls color
      },     // default brush color is black
      saveHandler: function (image, done) {
        if (_this.pageNum != null || undefined) {
          var pageCopy = allpages.find(page => { return page.page == _this.pageNum });
          _this.dataurl = image.asDataURL('image/jpeg', 2);
          if (pageCopy) {
            _this.PDFDetails.allpages.push({
              page: _this.pageNum,
              canvasdata: _this.dataurl
            });
            allpages.push({
              page: _this.pageNum,
              canvasdata: _this.dataurl
            });
//db.push code
            // console.log('Updated Page - ', pageNum, ' into array', _this.PDFDetails.allpages, 'and', _this.allpages);
          }
          // console.log('allpages canvas', _this.PDFDetails.allpages);
        }
        done(true);
      },
    });
    ptr.show(dataurl);
