### ISSUE TITLE
handling how_to_paste event

### ISSUE THREAD

**Issue by kishandonepudi** [ivictbor/painterro#26]
how to handle how_to_paste event to default as replace all..

and also open image is very slow when i done it in angular-ionic app, it keep on showing loading......

**Comment by ivictbor** [comment]
What image you are trying to open, can you please provide it here, and also please values - e.g. "opening of this image takes more then 5 seconds" etc.
Sorry, I  don't know what is how_to_paste event, need more details...

**Comment by kishandonepudi** [comment]
Thanks for the reply 

When i choose open image and select some image file, it alerts to choose as below screenshot.

![image](https://user-images.githubusercontent.com/17450660/44024879-266070a0-9f0c-11e8-8dbd-3a23f2838eb7.png)

I want to make it default as "**Replace all**"

**Comment by ivictbor** [comment]
Thanks, I think it's cool to have this feature. Maybe it's even better to implement it as option instead of event:
* First way: `how_to_paste_action: 'show_dialog'|'replace_all'|'paste_over'|'extend_right'|'extend_down' `. And you will need to define `how_to_paste_action: 'replace_all'` and default value will be  `how_to_paste_action: 'show_dialog'`.
* The second way implement array of visible actions:
`how_to_paste_actions: ['replace_all', 'paste_over', 'extend_right', 'extend_down']`, and if there will be only one action then we will just skip dialog. So in your case you will need use `how_to_paste_actions: ['replace_all']`

The second way is more flexible because allows to hide some options (I think some users may live without `extend down` and `extend right`), but also second way is less verbose and a little bit confused.

**Comment by kishandonepudi** [comment]
> Thanks, I think it's cool to have this feature. Maybe it's even better to implement it as option instead of event:
> 
> * First way: `how_to_paste_action: 'show_dialog'|'replace_all'|'paste_over'|'extend_right'|'extend_down'`. And you will need to define `how_to_paste_action: 'replace_all'` and default value will be  `how_to_paste_action: 'show_dialog'`.
> * The second way implement array of visible actions:
>   `how_to_paste_actions: ['replace_all', 'paste_over', 'extend_right', 'extend_down']`, and if there will be only one action then we will just skip dialog. So in your case you will need use `how_to_paste_actions: ['replace_all']`
> 
> The second way is more flexible because allows to hide some options (I think some users may live without `extend down` and `extend right`), but also second way is less verbose and may be little bit confusing.

i have tried defining how_to_paste_action: 'replace_all' but nothing changed.

my code is like 

`var ptr = Painterro({
      hiddenTools: ['crop', 'select', 'pixelize','rotate','open'],
      how_to_paste_action: 'replace_all',
      toolbarPosition: 'top',
      defaultTool: 'brush',
      defaultLineWidth: 8,
      defaultFontSize: 8,
      availableLineWidths: [1, 2, 4, 8, 16, 64],
      availableEraserWidths: [1, 2, 4, 8, 16, 64],
      availableFontSizes: [1, 2, 4, 8, 16, 64],
      activeColor: '#000000',
      colorScheme: {
        activeControl: '#e20214',
        inputText: '#000000', // change controls color
      },     // default brush color is black`

**Comment by kishandonepudi** [comment]
> var ptr = Painterro({
      hiddenTools: ['crop', 'select', 'pixelize','rotate','open'],
      how_to_paste_action: 'replace_all',
      toolbarPosition: 'top',
      defaultTool: 'brush',
      defaultLineWidth: 8,
      defaultFontSize: 8,
      availableLineWidths: [1, 2, 4, 8, 16, 64],
      availableEraserWidths: [1, 2, 4, 8, 16, 64],
      availableFontSizes: [1, 2, 4, 8, 16, 64],
      activeColor: '#000000',
      colorScheme: {
        activeControl: '#e20214',
        inputText: '#000000', // change controls color
      },     // default brush color is black

**Comment by kishandonepudi** [comment]
> Thanks, I think it's cool to have this feature. Maybe it's even better to implement it as option instead of event:
> 
> * First way: `how_to_paste_action: 'show_dialog'|'replace_all'|'paste_over'|'extend_right'|'extend_down'`. And you will need to define `how_to_paste_action: 'replace_all'` and default value will be  `how_to_paste_action: 'show_dialog'`.
> * The second way implement array of visible actions:
>   `how_to_paste_actions: ['replace_all', 'paste_over', 'extend_right', 'extend_down']`, and if there will be only one action then we will just skip dialog. So in your case you will need use `how_to_paste_actions: ['replace_all']`
> 
> The second way is more flexible because allows to hide some options (I think some users may live without `extend down` and `extend right`), but also second way is less verbose and may be little bit confusing.

I have tried like this but nothing improved..

> var ptr = Painterro({
      hiddenTools: ['crop', 'select', 'pixelize','rotate','open'],
      how_to_paste_action: 'replace_all',
      toolbarPosition: 'top',
      defaultTool: 'brush',
      defaultLineWidth: 8,
      defaultFontSize: 8,
      availableLineWidths: [1, 2, 4, 8, 16, 64],
      availableEraserWidths: [1, 2, 4, 8, 16, 64],
      availableFontSizes: [1, 2, 4, 8, 16, 64],
      activeColor: '#000000',
      colorScheme: {
        activeControl: '#e20214',
        inputText: '#000000', // change controls color
      },     // default brush color is black

**Comment by ivictbor** [comment]
added in 0.2.69. Please check readme

**Comment by kishandonepudi** [comment]
I have tried like the below,

how_to_paste_actions: ['replace_all'],


But it is not automatically selecting the **replace all** like below

![image](https://user-images.githubusercontent.com/17450660/49598673-2629e500-f9a5-11e8-9418-a53750e7925e.png)

**Comment by ivictbor** [comment]
@kishandonepudi thanks, really replace_all option screwed up =)

**Comment by ivictbor** [comment]
@kishandonepudi fixed, now values in readme and code are same
