### ISSUE TITLE
How i can add callback to Undo and Redo events?

### ISSUE THREAD

**Issue by Levhav** [ivictbor/painterro#36]
Hi, i want use this project for made collaborating painting on web page,
I want for this understand how i can add callback to Undo and Redo events, and how i can drawing to the canvas from js code.

**Comment by ivictbor** [comment]
@Levhav Hi, thanks for proposal, we will need to add it. Pretty easy, but requires to arrange some time. Btw you could do it by yourself, you just need to find events in code and trigger callbacks.

**Comment by ivictbor** [comment]
@Levhav callbacks are added in 0.2.69. Please check readme

To drow on Painterro canvas you can use `ctx` property of painterro instance, for example:

```
  window.p = Painterro({ }).show() 
  const ctx = window.p.ctx;

  ctx.beginPath();
  ctx.moveTo(0,0);
  ctx.lineTo(300,150);
  ctx.strokeStyle="#FF0000";
  ctx.stroke();
```
