### ISSUE TITLE
Save to local or send by email

### ISSUE THREAD

**Issue by jeromebg** [ivictbor/painterro#43]
Thx for this lovely script !
Would be great to have the possibility to save the canvas local or to send it by email ?
thx for your great work !

**Comment by ivictbor** [comment]
We can add the ability to save it locally, thanks for the suggestion

**Comment by ivictbor** [comment]
hi @jeromebg 
I thought about it feature, and came to decision that it should not be built-in feature. Please combine this code with save handler (read documentation)

```
 const link = document.createElement('a');
    link.download = fileName + '.png';
    console.log(canvas)
    canvas.toBlob(function(blob) {
        console.log(blob)
        link.href = URL.createObjectURL(blob);
        link.click();
    });
```
from https://stackoverflow.com/a/57385966/3479125

Or this https://stackoverflow.com/a/14011075/3479125

Same with email
