### ISSUE TITLE
[Doubt] Language Files

### ISSUE THREAD

**Issue by Leinad4Mind** [ivictbor/painterro#45]
Hi there, I am interested on providing PRs for Portuguese (Portugal and Brasil) and French languages but I want to know which filenames I should give. Portuguese-Portugal normally is just pt or pt-PT and Portuguese-Brasil is pt-BR and french just fr or fr-FR.

So it would be:

pt-PT.lang.js
pt-BR.lang.js
fr.lang.js

?

**Comment by ivictbor** [comment]
Hi, @Leinad4Mind thanks for the contribution! Your filenames look fine

**Comment by Leinad4Mind** [comment]
Btw on the readme file could you update the hiddenTools, it seems there is more tools now.

Thanks
