### ISSUE TITLE
Getting CORS policy error

### ISSUE THREAD

**Issue by paritoshcardinal** [ivictbor/painterro#53]
Is there is any way to set Access-Control-Allow-Origin for my domain because I am getting error "has been blocked by CORS policy: No 'Access-Control-Allow-Origin'". Thanks Paritosh

**Comment by ivictbor** [comment]
@paritoshcardinal Hi Paritosh
Sorry, painterro has no relation to your domain and you cors setup at all, this option controlled by some software which sents http responses. Painterro is just frontend library
