### ISSUE TITLE
Image Size Issue

### ISSUE THREAD

**Issue by pankajcardinal** [ivictbor/painterro#55]
When I upload image size 100 kb, after saving it becomes 700kb. I am not able to understand logic behind it. how can  it fix? Please suggest me.

**Comment by paritoshcardinal** [comment]
I am facing same issue. Uploading an image and after saving its becoming 10X image size. I guess it copying along with canvas not sure. Please help us out to resolve this major issue. Its effecting on application performance. Thanks!

**Comment by SeibelStan** [comment]
asDataURL('image/jpg') not affect image type, result is png!
If i replace all png in code to jpg, anyway result is png =\
Problem is very actually now for me, search decision.

**Comment by ivictbor** [comment]
@SeibelStan Please read documentation carefully https://github.com/ivictbor/painterro#format-and-quality. There is no such mime type as `image/jpg`, should be `image/jpeg`

@pankajcardinal please try defining quality of exported image and use `image/jpeg`, Read here https://github.com/ivictbor/painterro#format-and-quality
