### ISSUE TITLE
Major Issue 3MB image getting 22MB after save.

### ISSUE THREAD

**Issue by paritoshcardinal** [ivictbor/painterro#57]
There is a major issue when i am uploading and saving 3MB image its getting 22MB after save. It will slow my application if we go with this issue. Please resolve it asap. Thanks!

**Comment by ivictbor** [comment]
Thanks for issue posting, please debug saving chain in painterro and create PR for fix if you will find reason. Saving there is pretty simple it just involves builtin canvas methods

**Comment by SeibelStan** [comment]
My save handler:

saveHandler: function (image) {                   
    var tImg = new Image();
    tImg.src = image.asDataURL();
    tImg.onload = function () {
        ctx.drawImage(tImg, 0, 0); 
        var content = canvas.toDataURL('image/jpeg');
        $('.tool_ajupload_content').val(content);
        $('.fm_ajuploadhere').submit();
        $('[title="Close Painterro"]').click();
    }
}

asDataURL('image/jpg') do not affect type, return png anyway.

**Comment by ivictbor** [comment]
@SeibelStan There is no such mime type like `image/jpg' https://stackoverflow.com/a/37266399/3479125
`

**Comment by SeibelStan** [comment]
Где у меня jpg? Везде jpeg и в коде я значения по-умолчанию пробовал ставить на jpeg, всё равно png отдаёт, перегоняю через свой канвас, пока такой костыль.
asDataURL хоть принимает тип, реально его не применяет. Собранный исходник без сокращения имён давать не хочешь, так что даже не могу разобраться куда ставить. Я не фронтендер, в сборщики влазить не планировал как класс. Собранный жс отладить скорее всего могу.

**Comment by ivictbor** [comment]
@SeibelStan 
1. Then you made the wrong statement in a comment:
![image](https://user-images.githubusercontent.com/1838656/60814287-05757800-a19e-11e9-9f7b-7a47cd760132.png)
2. All unminified sources are in the repo and they require bundling, we have no other sources. The minified file is a result of bundler, it is not a source

**Comment by SeibelStan** [comment]
1. Неважно, всяко пробовал, и в параметр и в коде менял, в коменте просто опечатка, как-то же я сделал через свою канву в итоге.
2. Я понимаю что это не исходник, но в src подключается билд, и можно сделать билд без сокращения имён, не говори что невозможно.
3. Имеет смысл сделать жпег по-умолчанию, 99,9% там рисуют стрелочки на фотографиях потом неприятно удивляются что размер вырос в 10 раз. Для точной передачи есть блоб уже.

**Comment by ivictbor** [comment]
Tested on `index.html` test page, works exactly as designed for me. @SeibelStan I think you doing something wrong.

```
<button onclick="saveTest()">Save</button>
...
  function saveTest() {
    const u = window.p.imageSaver.asDataURL('image/jpeg');
    console.log('saved', u.length, u);
  }  
```

![image](https://user-images.githubusercontent.com/1838656/60816569-a9612280-a1a2-11e9-998d-dc8f20ebd1a2.png)
![image](https://user-images.githubusercontent.com/1838656/60816587-b2ea8a80-a1a2-11e9-8e0e-fad90e3581ff.png)


```
  function saveTest() {
    const u = window.p.imageSaver.asDataURL('image/png');
    console.log('saved', u.length, u);
  }  
```

![image](https://user-images.githubusercontent.com/1838656/60816689-e9280a00-a1a2-11e9-96b8-890da095e8b6.png)

Feel free to create an issue with specifying **exact** steps to reproduce
