### ISSUE TITLE
Any way to save the state of drawing pattern?

### ISSUE THREAD

**Issue by Rajan4436** [ivictbor/painterro#6]
Hi, is there any way to preserve the changes done on page load. To maintain a state or something like that. 
Also if I can pass the saved state to different route as parameters, to load another instance of painterro in that route, it would be great. 

Thanks.

**Comment by ivictbor** [comment]
Hi @Rajan4436 ,
sorry for long, response a had no access to PC so was not able to respond.
If I understand your task correctly you need to persist image between page loadings.
* You can get image as dataurl by calling `painterroInstance.imageSaver.asDataURL()`.
* You can save it to `localStorage`, or to your backend, or using filesystem API, etc. (`localStorage` have some quota https://arty.name/localstorage.html, so it will not work for large images)
* then just pass dataurl to show method (show method accepts all types of URLs: plain like `http://something/file.jpg` or data `data:...`)
* I also added `changeHandler` param so you can define handler which will be fired after each change on canvas 
So it can look something like this:
```
Painterro({
    changeHandler: function (state) {
      localStorage.setItem('painterroImage', this.imageSaver.asDataURL())
    }
  }).show(localStorage.getItem('painterroImage'));
```
Fiddle: https://jsfiddle.net/vanbrosh/zL4ay02c/1/

**Comment by Rajan4436** [comment]
Awesome
