### ISSUE TITLE
translation parameter

### ISSUE THREAD

**Issue by Jesfery** [ivictbor/painterro#8]
Hi Ivan,

I was trying to use the translation parameter to alter a couple of the tool's tooltips, but I get the following runtime error when I attempt to use it. 

Uncaught TypeError: Cannot read property 'get' of undefined

I'm not sure, but I think it might be the way Translation is imported at the top of params.js. Changing it to `import { Translation } from './translation';` seemed to fix it for me, but I'm not familiar with how the import stuff works.

Thanks

Sean

**Comment by ivictbor** [comment]
Hi @Jesfery 
Thanks for reporting
Yes you are right, it can be fixed by changing `Translation  -> { Translation }` or export Translation class as default (what I intended to do, but missed this)

**Comment by Jesfery** [comment]
Excellent. Thanks for that!

**Comment by Jesfery** [comment]
Yep. That seems to be sorted now. Thanks again.
